export type Language = 'en' | 'es'
export type AppView = 'dashboard' | 'notes' | 'voiceMemos'

export const copy = {
  en: {
    workspace: 'workspace',
    settings: 'Settings',
    language: 'Language',
    lightMode: 'Light mode',
    dashboard: 'Dashboard',
    mondayDashboard: 'Monday dashboard',
    commandCenter: 'Daily command center',
    newTask: 'New task',
    totalTasks: 'Total tasks',
    completed: 'Completed',
    notes: 'Notes',
    voiceMemos: 'Voice memos',
    todoQueue: 'Todo queue',
    all: 'All',
    active: 'Active',
    addQuickTask: 'Add a quick task',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    add: 'Add',
    edit: 'Edit',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
    editTodo: 'Edit task',
    editNote: 'Edit note',
    remove: 'Remove',
    voiceMemo: 'Voice memo',
    stop: 'Stop',
    record: 'Record',
    attachment: 'Attachment',
    noVoiceMemo: 'No voice memo attached yet.',
    play: 'Play',
    pause: 'Pause',
    noteTitle: 'Note title',
    writeNote: 'Write a quick thought, summary, or plan...',
    tags: 'Tags separated by commas',
    saveNote: 'Save note',
    listen: 'Listen',
    delete: 'Delete',
    voiceLibrary: 'Saved voice memos',
    noSavedMemos: 'Your saved voice memos will appear here.',
    memoName: 'Name this voice memo',
    saveMemo: 'Save to library',
    memoSaved: 'Voice memo saved to your library.',
  },
  es: {
    workspace: 'espacio de trabajo',
    settings: 'Ajustes',
    language: 'Idioma',
    lightMode: 'Modo claro',
    dashboard: 'Inicio',
    mondayDashboard: 'Panel del lunes',
    commandCenter: 'Centro de actividad',
    newTask: 'Nueva tarea',
    totalTasks: 'Tareas totales',
    completed: 'Completadas',
    notes: 'Notas',
    voiceMemos: 'Notas de voz',
    todoQueue: 'Lista de tareas',
    all: 'Todas',
    active: 'Activas',
    addQuickTask: 'Añadir una tarea',
    low: 'Baja',
    medium: 'Media',
    high: 'Alta',
    add: 'Añadir',
    edit: 'Editar',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
    editTodo: 'Editar tarea',
    editNote: 'Editar nota',
    remove: 'Quitar',
    voiceMemo: 'Nota de voz',
    stop: 'Detener',
    record: 'Grabar',
    attachment: 'Adjunto',
    noVoiceMemo: 'Todavía no hay ninguna nota de voz.',
    play: 'Reproducir',
    pause: 'Pausar',
    noteTitle: 'Título de la nota',
    writeNote: 'Escribe una idea, resumen o plan...',
    tags: 'Etiquetas separadas por comas',
    saveNote: 'Guardar nota',
    listen: 'Escuchar',
    delete: 'Eliminar',
    voiceLibrary: 'Notas de voz guardadas',
    noSavedMemos: 'Tus notas de voz guardadas aparecerán aquí.',
    memoName: 'Ponle nombre a esta nota de voz',
    saveMemo: 'Guardar en la biblioteca',
    memoSaved: 'Nota de voz guardada en tu biblioteca.',
  },
} satisfies Record<Language, Record<string, string>>

export type AppCopy = typeof copy.en
